<?php
/**
 * Created by PhpStorm.
 * User: bvanleeuwen
 * Date: 21/06/2017
 * Time: 14:35
 */

namespace gillz\imageViewer;

use yii\base\Widget;
use yii\base\InvalidConfigException;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

class ImageViewer extends Widget {

    public static $imageViewerHasBeenLoaded = false;

    /**
     * @var string The image source for the image that will be displayed
     * This variable will be used to render the image that the user can click
     */
    public $imageSource;

    /**
     * @var string|null The image source for the high res version of the `self::$imageSource` variable
     * If no high res image is passed to this variable the `self::$imageSource` variable will be used for this variable
     */
    public $imageSourceHighRes = null;

    public $options = [];

    public function init() {
        parent::init();

        // Check if all the needed variables are set
        $this->_checkVariables();

        // Check image the high res source has been set
        if ($this->imageSourceHighRes === null)
            $this->imageSourceHighRes = $this->imageSource;

        // Build this instance ID
        $this->options['id'] = 'image-viewer-'.Widget::$counter;
        Widget::$counter++;

        // Merge the user option array with the array we build
        $this->options = ArrayHelper::merge([
            'class' => 'img-responsive',
            'data' => [
                'high-res-src' => $this->imageSourceHighRes,
            ],
        ], $this->options);

        // Register the javascript
        $this->_registerJavascript();
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        return $this->_renderHtml();
    }

    /**
     * Check if all the variables that are needed for this plugin have been set
     */
    protected function _checkVariables() {
        if ($this->imageSource === null)
            // No image source has been provided, throw new error
            throw new InvalidConfigException('Gillz ImageViewer: The image source has not been provided');
    }

    protected function _renderHtml() {
        return Html::img($this->imageSource, $this->options);
    }

    protected function _registerJavascript() {
        // Check if the image viewer has been loaded
        if (! self::$imageViewerHasBeenLoaded) {
            // Load the AssetBundle
            AssetBundle::register($this->view);
            // Register the ImageViewer variale
            $this->view->registerJs('var viewer = ImageViewer();');
        }

        $this->view->registerJs("
        $('#{$this->options['id']}').click(function () {
            var imgSrc = this.src,
                highResolutionImage = $(this).data('high-res-img');
            viewer.show(imgSrc, highResolutionImage);
        });");
    }
}